### ISSUE TITLE
Crash in `all_path_reachability_prove` on some configurations with abstracted cells

### ISSUE THREAD

**Issue by nwatson22** [runtimeverification/pyk#259]
## Steps to reproduce:

1. Create files:

`kcfg/test.py`

```py
from pyk.kast.inner import KApply
from pyk.kcfg.tui import KCFGViewer
from pyk.kcfg.explore import KCFGExplore
from pyk.kcfg.kcfg import KCFG
from pyk.ktool.kprove import KProve
from pathlib import Path

kprove = KProve(definition_dir="verification")

claim_id = "main"
spec_file = Path("simple-spec.k")
spec_module = spec_file.name.removesuffix('.k').removesuffix('.md').upper()
claim_label = f'{spec_module}.{claim_id}'
claims = kprove.get_claims(spec_file, spec_module_name=spec_module, claim_labels=[claim_label])

cfg = KCFG.from_claim(kprove.definition, claims[0])
cfg_id = f'{claim_label}.kfcg'

with KCFGExplore(kprove, 7777) as kcfg_explore:
    kcfg_explore.all_path_reachability_prove(
        cfg_id,
        cfg,
        cfg_dir=Path("output"),
        terminal_rules=['AVM-EXECUTION.starttx', 'AVM-EXECUTION.endtx', 'AVM-PANIC.panic'],
    )


kcfg = KCFGExplore.read_cfg(cfg_id, Path("output"))


app = KCFGViewer(kcfg=kcfg, kprint=kprove, minimize=False)
app.run()
```

`pyproject.toml`

```toml
[tool.poetry]
name = "kcfg"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.10"
pyk = { git = "https://github.com/runtimeverification/pyk.git", tag="v0.1.173" }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

```

`verification.k`

```k
module VERIFICATION
  imports INT

  configuration 
  <k> $PGM:K </k>
  <outerCell>
    <cell1> 0 </cell1>
    <cell2> 0 </cell2>
  </outerCell>
endmodule
```

`simple-spec.k`

```k
module SIMPLE-SPEC
  imports VERIFICATION

  claim [main]: 
  <k> _ => ?_ </k>
  <outerCell>
     _ => ?_
  </outerCell>

endmodule
```

2. install pyk
`poetry -C kcfg install`

3. create kcfg output dir
`mkdir output`

4. kompile
`kompile --backend haskell verification.k -o verification --emit-json`

5. run pyk prover
`poetry -C kcfg run python kcfg/test.py`

## Expected result:
KCFG is written to file and viewer is opened

## Actual result:
```
Traceback (most recent call last):
  File "/home/noah/dev/kcfg2/kcfg/test.py", line 16, in <module>
    cfg = KCFG.from_claim(kprove.definition, claims[0])
  File "/home/noah/.cache/pypoetry/virtualenvs/kcfg--0RjRrOz-py3.10/lib/python3.10/site-packages/pyk/kcfg/kcfg.py", line 263, in from_claim
    claim_body = rename_generated_vars(claim_body)
  File "/home/noah/.cache/pypoetry/virtualenvs/kcfg--0RjRrOz-py3.10/lib/python3.10/site-packages/pyk/kast/manip.py", line 672, in rename_generated_vars
    cvar = cvars[0]
IndexError: list index out of range
/usr/lib/python3.10/tempfile.py:999: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/tmp05mv1hgf'>
  _warnings.warn(warn_message, ResourceWarning)
```

## Notes:
I'm not sure if this is an actual bug, or something wrong with my installation, or if it's documented somewhere that these sorts of claims aren't supposed to work with the pyk prover. I got the same crash in evm-semantics and avm-semantics, but it doesn't seem to be crashing the CI jobs in those projects. I would be interested to know if it is replicable on someone else's machine.

**Comment by Scott-Guest** [comment]
I was able to reproduce this on my on my machine, investigating further

**Comment by Scott-Guest** [comment]
Per discussion with @tothtamas28, for the short term, we'll just rewrite `rename_generated_vars` to traverse the AST instead of using `split_config_from`, allowing it to handle cases such as the one here.
